### ISSUE TITLE
No slip boundary conditions not being implemented

### ISSUE THREAD

**Issue by suyash309** [NOAA-GFDL/MOM6#230] opened 2015-10-05 17:57 UTC
We are running a zonally re-entrant setup on a spherical grid forced by restoring buoyancy at the surface. It seems that the model is not conserving zonal angular momemtum. We have `NOSLIP = True` in the MOM_input file. But when we look at the output, the model seems to have free slip turned on instead. This is crucial because any numerically generated spurious angular momentum is expected to be dissipated by friction at the boundaries. We believe this is not happening because of free slip condition.

The documentation does say that implementation of no slip condition is not as clean as free slip. So I'm wondering if the implementation of no slip conditions still not complete. Or is there something we might be missing from our setup? Let me know if you need to take a closer look at our setup.

**Comment by pittwolfe** [comment] 2015-10-05 18:14
A few more details: the domain is zonally periodic, 22 degrees wide and 60 degrees N/S extent. The forcing is relaxation to a zonally symmetric buoyancy profile equivalent to a uniform temperature of 20ºC south of 20ºN, 6ºC north of 40ºN and a linear ramp between the two. Even though the initial conditions are horizontally uniform and at rest, the model develops a rather hefty zonal current of transporting around 120 Sv. (See attached figure) Since the zonal momentum is initially zero and there are no sources of zonal momentum, one would expect a purely baroclinic current or, if there's enough nonlinearity, banded jets with a net zero zonal transport over the whole domain. (Note that the final flow is steady and zonally symmetric, so there are no eddies or physical instabilities.) 

![psiu](https://cloud.githubusercontent.com/assets/4522204/10288288/f130a0bc-6b65-11e5-944f-e9750e874853.png)

Obviously, MOM is not conserving zonal momentum. This is not itself too worrying, since it's hard to conserve momentum in spherical coordinates. One usually hopes that dissipation would destroy the excess momentum generated by the numerics and you'd end up with a somewhat physical final state. In this geometry, the only way to dissipate momentum are drag against the sides and bottom. We are using quadratic bottom drag, but the vertically sheared flow has arranged itself so the bottom velocities are zero. This leaves side drag. We have NO_SLIP = True, but inspection of the zonal velocity (also on attached figure) shows that the boundary velocity is *not* zero, though its normal derivative is. Thus, the model seems to be using free slip boundary conditions even though no slip conditions are requested. Comments in the configuration file recommend against using no-slip because free-slip conditions are more "natural" on a C grid, but in this relatively simple test case, the combination of free-slip and lack of momentum conservation leads to a completely unphysical solution. No slip conditions are compatible with C grid finite volume codes (even for biharmonic friction) and are implemented in, e.g., the MITgcm.

Are there plans to implement no-slip in MOM6? Am I just misinterpreting these results? If no-slip conditions are really implemented in MOM6, how can they be turned on (since setting NO_SLIP = True seems not to work)?

Thanks,
Christopher

**Comment by adcroft** [comment] 2015-10-05 19:38
@suyash309 Can you make the configuration directory available so we can look at the setup? Or post  MOM_parameter_doc.short ...

**Comment by suyash309** [comment] 2015-10-05 20:08
I'm trying to upload it all on Github but am not able to. I'll figure it out. For the time being i'm pasting the MOM_parameter_doc.short here.

```
! This file was written by the model and records the non-default parameters used at run-time.
NIGLOBAL = 100                  !
                                ! The total number of thickness grid points in the
                                ! x-direction in the physical domain. With STATIC_MEMORY_
                                ! this is set in MOM_memory.h at compile time.
NJGLOBAL = 300                  !
                                ! The total number of thickness grid points in the
                                ! y-direction in the physical domain. With STATIC_MEMORY_
                                ! this is set in MOM_memory.h at compile time.

! === module MOM_grid ===
! Parameters providing information about the vertical grid.
RHO_0 = 1031.0                  !   [kg m-3] default = 1035.0
                                ! The mean ocean density used with BOUSSINESQ true to
                                ! calculate accelerations and the mass for conservation
                                ! properties, or with BOUSSINSEQ false to convert some
                                ! parameters from vertical units of m to kg m-2.
NK = 25                         !   [nondim]
                                ! The number of model layers.

! === module MOM_verticalGrid ===
! Parameters providing information about the vertical grid.

! === module MOM ===
ENABLE_THERMODYNAMICS = False   !   [Boolean] default = True
                                ! If true, Temperature and salinity are used as state
                                ! variables.
THICKNESSDIFFUSE = True         !   [Boolean] default = False
                                ! If true, interface heights are diffused with a
                                ! coefficient of KHTH.
DT = 7200.0                     !   [s]
                                ! The (baroclinic) dynamics time step.  The time-step that
                                ! is actually used will be an integer fraction of the
                                ! forcing time-step (DT_FORCING in ocean-only mode or the
                                ! coupling timestep in coupled mode.)
DT_THERM = 2.16E+04             !   [s] default = 7200.0
                                ! The thermodynamic and tracer advection time step.
                                ! Ideally DT_THERM should be an integer multiple of DT
                                ! and less than the forcing or coupling time-step, unless
                                ! THERMO_SPANS_COUPLING is true, in which case DT_THERM
                                ! can be an integer multiple of the coupling timestep.  By
                                ! default DT_THERM is set to DT.
DTBT_RESET_PERIOD = 0.0         !   [s] default = 2.16E+04
                                ! The period between recalculations of DTBT (if DTBT <= 0).
                                ! If DTBT_RESET_PERIOD is negative, DTBT is set based
                                ! only on information available at initialization.  If
                                ! dynamic, DTBT will be set at least every forcing time
                                ! step, and if 0, every dynamics time step.  The default is
                                ! set by DT_THERM.  This is only used if SPLIT is true.
SAVE_INITIAL_CONDS = True       !   [Boolean] default = False
                                ! If true, write the initial conditions to a file given
                                ! by IC_OUTPUT_FILE.

! === module MOM_tracer_registry ===

! === module MOM_tracer_flow_control ===

! === module MOM_grid_init ===
GRID_CONFIG = "spherical"       !
                                ! A character string that determines the method for
                                ! defining the horizontal grid.  Current options are:
                                !     mosaic - read the grid from a mosaic (supergrid)
                                !              file set by GRID_FILE.
                                !     cartesian - use a (flat) Cartesian grid.
                                !     spherical - use a simple spherical grid.
                                !     mercator - use a Mercator spherical grid.
SOUTHLAT = 0.0                  !   [degrees]
                                ! The southern latitude of the domain.
LENLAT = 60.0                   !   [degrees]
                                ! The latitudinal length of the domain.
WESTLON = -22.0                 !   [degrees] default = 0.0
                                ! The western longitude of the domain.
LENLON = 22.0                   !   [degrees]
                                ! The longitudinal length of the domain.
TOPO_CONFIG = "flat"            !
                                ! This specifies how bathymetry is specified:
                                !     file - read bathymetric information from the file
                                !       specified by (TOPO_FILE).
                                !     flat - flat bottom set to MAXIMUM_DEPTH.
                                !     bowl - an analytically specified bowl-shaped basin
                                !       ranging between MAXIMUM_DEPTH and MINIMUM_DEPTH.
                                !     spoon - a similar shape to 'bowl', but with an vertical
                                !       wall at the southern face.
                                !     halfpipe - a zonally uniform channel with a half-sine
                                !       profile in the meridional direction.
                                !     benchmark - use the benchmark test case topography.
                                !     DOME - use a slope and channel configuration for the
                                !       DOME sill-overflow test case.
                                !     DOME2D - use a shelf and slope configuration for the
                                !       DOME2D gravity current/overflow test case.
                                !     seamount - Gaussian bump for spontaneous motion test case.
                                !     Phillips - ACC-like idealized topography used in the Phillips config.
                                !     USER - call a user modified routine.
MINIMUM_DEPTH = 1.0             !   [m] default = 0.0
                                ! The minimum depth of the ocean.
MAXIMUM_DEPTH = 1000.0          !   [m]
                                ! The maximum depth of the ocean.
COORD_CONFIG = "USER"           !
                                ! This specifies how layers are to be defined:
                                !     file - read coordinate information from the file
                                !       specified by (COORD_FILE).
                                !     linear - linear based on interfaces not layers
                                !     layer_ref - linear based on layer densities
                                !     ts_ref - use reference temperature and salinity
                                !     ts_range - use range of temperature and salinity
                                !       (T_REF and S_REF) to determine surface density
                                !       and GINT calculate internal densities.
                                !     gprime - use reference density (RHO_0) for surface
                                !       density and GINT calculate internal densities.
                                !     ts_profile - use temperature and salinity profiles
                                !       (read from COORD_FILE) to set layer densities.
                                !     USER - call a user modified routine.
THICKNESS_CONFIG = "USER1"      !
                                ! A string that determines how the initial layer
                                ! thicknesses are specified for a new run:
                                !     file - read interface heights from the file specified
                                !     thickness_file - read thicknesses from the file specified
                                !       by (THICKNESS_FILE).
                                !     coord - determined by ALE coordinate.
                                !     uniform - uniform thickness layers evenly distributed
                                !       between the surface and MAXIMUM_DEPTH.
                                !     DOME - use a slope and channel configuration for the
                                !       DOME sill-overflow test case.
                                !     benchmark - use the benchmark test case thicknesses.
                                !     search - search a density profile for the interface
                                !       densities. This is not yet implemented.
                                !     circle_obcs - the circle_obcs test case is used.
                                !     DOME2D - 2D version of DOME initialization.
                                !     adjustment2d - TBD AJA.
                                !     sloshing - TBD AJA.
                                !     seamount - TBD AJA.
                                !     rossby_front - a mixed layer front in thermal wind balance.
                                !     USER - call a user modified routine.
SPONGE = True                   !   [Boolean] default = False
                                ! If true, sponges may be applied anywhere in the domain.
                                ! The exact location and properties of those sponges are
                                ! specified via SPONGE_CONFIG.
SPONGE_CONFIG = "USER2"         ! default = "file"
                                ! A string that sets how the sponges are configured:
                                !     file - read sponge properties from the file
                                !       specified by (SPONGE_FILE).
                                !     DOME - use a slope and channel configuration for the
                                !       DOME sill-overflow test case.
                                !     USER - call a user modified routine.
!Total sponge columns = 2000    !
                                ! The total number of columns where sponges are applied.

! === module MOM_MEKE ===

! === module MOM_wave_speed ===

! === module MOM_lateral_mixing_coeffs ===

! === module MOM_set_visc ===
HBBL = 20.0                     !   [m]
                                ! The thickness of a bottom boundary layer with a
                                ! viscosity of KVBBL if BOTTOMDRAGLAW is not defined, or
                                ! the thickness over which near-bottom velocities are
                                ! averaged for the drag law if BOTTOMDRAGLAW is defined
                                ! but LINEAR_DRAG is not.
DRAG_BG_VEL = 0.05              !   [m s-1] default = 0.0
                                ! DRAG_BG_VEL is either the assumed bottom velocity (with
                                ! LINEAR_DRAG) or an unresolved  velocity that is
                                ! combined with the resolved velocity to estimate the
                                ! velocity magnitude.  DRAG_BG_VEL is only used when
                                ! BOTTOMDRAGLAW is defined.
BBL_THICK_MIN = 0.1             !   [m] default = 0.0
                                ! The minimum bottom boundary layer thickness that can be
                                ! used with BOTTOMDRAGLAW. This might be
                                ! Kv / (cdrag * drag_bg_vel) to give Kv as the minimum
                                ! near-bottom viscosity.
NOSLIP = True                   !   [Boolean] default = False
                                ! If true, no slip boundary conditions are used; otherwise
                                ! free slip boundary conditions are assumed. The
                                ! implementation of the free slip BCs on a C-grid is much
                                ! cleaner than the no slip BCs. The use of free slip BCs
                                ! is strongly encouraged, and no slip BCs are not used with
                                ! the biharmonic viscosity.

! === module MOM_hor_visc ===
LAPLACIAN = True                !   [Boolean] default = False
                                ! If true, use a Laplacian horizontal viscosity.
KH = 1.0E+04                    !   [m2 s-1] default = 0.0
                                ! The background Laplacian horizontal viscosity.
BIHARMONIC = False              !   [Boolean] default = True
                                ! If true, use a biharmonic horizontal viscosity.
                                ! BIHARMONIC may be used with LAPLACIAN.

! === module MOM_vert_friction ===
HMIX_FIXED = 20.0               !   [m]
                                ! The prescribed depth over which the near-surface
                                ! viscosity and diffusivity are elevated when the bulk
                                ! mixed layer is not used.
KV = 1.0E-04                    !   [m2 s-1]
                                ! The background kinematic viscosity in the interior.
                                ! The molecular value, ~1e-6 m2 s-1, may be used.
KVML = 0.01                     !   [m2 s-1] default = 1.0E-04
                                ! The kinematic viscosity in the mixed layer.  A typical
                                ! value is ~1e-2 m2 s-1. KVML is not used if
                                ! BULKMIXEDLAYER is true.  The default is set by KV.
MAXVEL = 10.0                   !   [m s-1] default = 3.0E+08
                                ! The maximum velocity allowed before the velocity
                                ! components are truncated.

! === module MOM_barotropic ===
BT_STRONG_DRAG = True           !   [Boolean] default = False
                                ! If true, use a stronger estimate of the retarding
                                ! effects of strong bottom drag, by making it implicit
                                ! with the barotropic time-step instead of implicit with
                                ! the baroclinic time-step and dividing by the number of
                                ! barotropic steps.

! === module MOM_thickness_diffuse ===
KHTH = 1.0E+04                  !   [m2 s-1] default = 0.0
                                ! The background horizontal thickness diffusivity.

! === module MOM_mixed_layer_restrat ===
Z_OUTPUT_GRID_FILE = "zcoord.nc" ! default = ""
                                ! The file that specifies the vertical grid for
                                ! depth-space diagnostics, or blank to disable
                                ! depth-space output.
!NK_ZSPACE (from file) = 50     !   [nondim]
                                ! The number of depth-space levels.  This is determined
                                ! from the size of the variable zw in the output grid file.

! === module MOM_diabatic_driver ===
! The following parameters are used for diabatic processes.
KD = 1.0E-04                    !   [m2 s-1]
                                ! The background diapycnal diffusivity of density in the
                                ! interior. Zero or the molecular value, ~1e-7 m2 s-1,
                                ! may be used.

! === module MOM_kappa_shear ===
! Parameterization of shear-driven turbulence following Jackson, Hallberg and Legg, JPO 2008

! === module MOM_KPP ===
! This is the MOM wrapper to CVmix:KPP
! See http://code.google.com/p/cvmix/

! === module MOM_diffConvection ===
! This module implements enhanced diffusivity as a
! function of static stability, N^2.
CONVECTION%
%CONVECTION

! === module MOM_entrain_diffusive ===

! === module MOM_regularize_layers ===

! === module MOM_tracer_advect ===

! === module MOM_tracer_hor_diff ===

! === module MOM_surface_forcing ===
VARIABLE_WINDS = False          !   [Boolean] default = True
                                ! If true, the winds vary in time after the initialization.
BUOY_CONFIG = "USER"            !
                                ! The character string that indicates how buoyancy forcing
                                ! is specified. Valid options include (file), (zero),
                                ! (linear), (USER), and (NONE).
WIND_CONFIG = "zero"            !
                                ! The character string that indicates how wind forcing
                                ! is specified. Valid options include (file), (2gyre),
                                ! (1gyre), (gyres), (zero), and (USER).
RESTOREBUOY = True              !   [Boolean] default = False
                                ! If true, the buoyancy fluxes drive the model back
                                ! toward some specified surface state with a rate
                                ! given by FLUXCONST.
FLUXCONST = 2.0                 !   [m day-1]
                                ! The constant that relates the restoring surface fluxes
                                ! to the relative surface anomalies (akin to a piston
                                ! velocity).  Note the non-MKS units.

! === module user_surface_forcing ===

! === module MOM_sum_output ===

! === module MOM_main (MOM_driver) ===
DT_FORCING = 8.64E+04           !   [s] default = 7200.0
                                ! The time step for changing forcing, coupling with other
                                ! components, or potentially writing certain diagnostics.
                                ! The default value is given by DT.
DAYMAX = 7.3E+04                !   [days]
                                ! The final time of the whole simulation, in units of
                                ! TIMEUNIT seconds.  This also sets the potential end
                                ! time of the present run segment if the end time is
                                ! not set via ocean_solo_nml in input.nml.
RESTART_CONTROL = 3             ! default = 1
                                ! An integer whose bits encode which restart files are
                                ! written. Add 2 (bit 1) for a time-stamped file, and odd
                                ! (bit 0) for a non-time-stamped file. A non-time-stamped
                                ! restart file is saved at the end of the run segment
                                ! for any non-negative value.
RESTINT = 500.0                 !   [days] default = 0.0
                                ! The interval between saves of the restart file in units
                                ! of TIMEUNIT.  Use 0 (the default) to not save
                                ! incremental restart files at all.
ENERGYSAVEDAYS = 1.0            !   [days] default = 8.64E+04
                                ! The interval in units of TIMEUNIT between saves of the
                                ! energies of the run and other globally summed diagnostics.
REPORT_UNUSED_PARAMS = True     !   [Boolean] default = False
                                ! If true, report any parameter lines that are not used
                                ! in the run.
```

**Comment by MJHarrison-GFDL** [comment] 2015-10-05 20:31
@suyash309 Can you also provide the sponge/forcing and initial condition files? You should be able to create your own fork on Github then push your changes, otherwise just send the files as an attachment.

**Comment by suyash309** [comment] 2015-10-05 23:51
@MJHarrison-GFDL, @adcroft  I edited my previous post. There are links to everything there. Thank you for your help.

**Comment by adcroft** [comment] 2015-10-06 01:57
I'm wondering about `BT_STRONG_DRAG = True`. This is an option within the barotropic-baroclinic split which has a lot of options due to the extended development of the algorithm. It could be overestimating the bottom drag and causing the weirdness. Can you see if setting it to False helps?

**Comment by suyash309** [comment] 2015-10-06 02:46
I've changed it to `BT_STRONG_DRAG = False`. I'll update here sometime tomorrow when I get some results.

**Comment by MJHarrison-GFDL** [comment] 2015-10-07 14:39
Did you consider moving the sponge away from the boundary?

**Comment by suyash309** [comment] 2015-10-07 14:54
You mean extending it meridionally to, say, 10N instead of the current 4N?

**Comment by MJHarrison-GFDL** [comment] 2015-10-07 15:03
Sorry, what I meant to say was that the *jet*  should be away from the
boundary.

I don't yet fully understand the problem here. If the desired solution is
no flow at the boundary, this seems inconsistent with having a jet only a
few grid points away.

**Comment by pittwolfe** [comment] 2015-10-07 15:59
The problem *is* the jet. We only specify buoyancy forcing at the surface and southern sponge and  forcing and sponges are zonally uniform, so there should be no source of zonal momentum. Therefore the jet is not there because of the forcing and there is no incompatibility between the forcing and boundary condition. Even if the jet were formed by some turbulent inverse cascade, the tangential flow should go to zero at the boundary due to no slip. What we see, however, is that the normal derivative of the tangential velocity goes to zero, suggesting that the model is giving us free-slip boundary conditions even though we asked for no-slip boundary conditions.

**Comment by Hallberg-NOAA** [comment] 2015-10-08 21:30
Hi Christopher and Suyash,
    
      Yes, you are absolutely right that the coastal lateral stresses
    probably are being zeroed out in your idealized test case, depending
    on how the layer thicknesses are being set in the halo points on
    land.  
    
      This has been a good discussion, that others might find helpful. 
    I originally encoded the no-slip boundary conditions, so perhaps I
    can comment on a number of issues that have arisen in this
    conversation thread.
    
      1) MOM6 is written with the intention that it conserves angular
    momentum pretty well. For example, conservation of angular momentum
    dictates the structure of the lateral stress tensor calculations in
    MOM6. However, a quadratic or linear bottom drag term or flow around
    bathymetric features can be effective ways to extract angular
    momentum from the solid earth if there is any near-bottom flow (as
    is usually the case). However I do not think that we have carefully
    examined this in all possible cases, so if there is clear evidence
    that this is not the case, we would like to have that drawn to our
    intention.  (The "pretty well" has to do with the deliberate use of
    different definitions of the layer thickness at velocity points
    depending on the flow direction and speed and relative thicknesses
    of adjacent points, but that is a very long a detailed technical
    discussion, much of which will appear in the MOM6 documentation
    paper that we are writing.
    
      2) The no-slip boundary conditions appear in the code in two
    places - in the estimate of relative vorticity at boundaries, and in
    the estimate of the shears at the boundaries (as determined by a 2-d
    land-mask). On a C-grid they do not dictate that the tangential
    velocity is actually 0 at any explicitly modeled location.
    
      3) The ocean has no vertical sides. Density surfaces end where
    they intersect the (usually sloping) bottom or the free surface. To
    conserve angular momentum, we write the horizontal viscosity term on
    a C-grid as 
      du / dt = 1/h_u Div([h_q K_q, h_h K_h] Grad u)
    where u is the velocity, h_u is an estimate of the layer thickness
    at velocity points, h_q is an estimate of the thickness at vorticity
    points, h_h is the thickness at thickness points, and [K_h, K_q] are
    the Laplacian viscosities at the thickness and vorticity points. 
    Everything except for h_q and h_u are well defined from 2nd order
    staggered discretizations or the C-grid variables themselves. 
    Conservation of angular momentum requires that the same h_q appear
    in the u- and v- equations, and we have chosen to use simple
    arithmetic mean thicknesses for h_u in this term. Ensuring a finite
    acceleration when one or more of these thicknesses at velocity
    points go to 0 requires that the h_q also go to 0 in these
    circumstances. Therefore, we use the harmonic mean of the harmonic
    mean of the 2 values of h_u and harmonic mean of the 2 values of h_v
    (see line ~466 of MOM_hor_visc.F90, which starts hq = ...).  The
    harmonic mean of A and B is 2 A B / (A + B), and it has the nice
    property that it is a second order accurate average of A and B, but
    goes to 2 A when A << B.  This works well, but we do not
    currently apply land masks, and setting h over land to 0 has the
    effect of setting h_q at coastlines to 0, and disabling the fluxes
    with a no-slip boundary condition.
    
     4) For the most part, in MOM6 we implement strong "lateral" drag
    via a vertical boundary condition with the CHANNEL_DRAG scheme,
    which calculates the bottom drag on a cell that partially intersects
    a sloping bottom.  This seems like the right approach for realistic
    simulations, but it obviously is not doing what we would like for
    idealized vertical-walled oceans.
    
     5) Properly implementing a no-slip boundary condition will require
    changing the definition of h_q at coastal points using the (2-d)
    land-sea masks to determine when to replace the thicknesses of
    masked velocity points with values that are temporarily extrapolated
    from unmasked neighbors. This should work well enough for straight
    or convex coastlines, but will introduce some (probably acceptable)
    cross-contamination of u- and v- thicknesses at concave corners in
    coastlines.  Once we have written and tested this code modification,
    we will be closing out this issue.
    
      Hopefully all this is helpful!
    
      - Bob Hallberg
    
    p.s., The BT_STRONG_DRAG only pertains to bottom drag was a red
    herring in this case.
      
    On 10/07/2015 11:59 AM, Christopher L. Pitt Wolfe wrote:
    
      The problem is the jet. We only specify buoyancy
        forcing at the surface and southern sponge and forcing and
        sponges are zonally uniform, so there should be no source of
        zonal momentum. Therefore the jet is not there because of the
        forcing and there is no incompatibility between the forcing and
        boundary condition. Even if the jet were formed by some
        turbulent inverse cascade, the tangential flow should go to zero
        at the boundary due to no slip. What we see, however, is that
        the normal derivative of the tangential velocity goes to zero,
        suggesting that the model is giving us free-slip boundary
        conditions even though we asked for no-slip boundary conditions.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by StephenGriffies** [comment] 2015-10-09 01:55
Hi,

I am only vaguely following the stencil details.  But the discussion of
spurious momentum sources makes me ask the following, perhaps off-the-mark
questions, but wishing to be sure we are passing the "laugh test".

With flat isopycnals and no momentum or buoyancy forcing at the ocean
surface, does MOM6 keep the flow static if there is a vertical wall?  What
about sloping walls?  Do answers to these questions depend on whether
free-slip, no-slip, bottom drag, etc?

Seems that the physically correct behaviour is static flow with horizontal
isopycnals will stay static, regardless the frictional boundary
conditions.  Capisce?

Steve



On Thu, Oct 8, 2015 at 5:30 PM, Robert Hallberg <notifications@github.com>
wrote:

>
>
>
>
>
> Hi Christopher and Suyash,
>
>   Yes, you are absolutely right that the coastal lateral stresses
> probably are being zeroed out in your idealized test case, depending
> on how the layer thicknesses are being set in the halo points on
> land.
>
>   This has been a good discussion, that others might find helpful.
> I originally encoded the no-slip boundary conditions, so perhaps I
> can comment on a number of issues that have arisen in this
> conversation thread.
>
>   1) MOM6 is written with the intention that it conserves angular
> momentum pretty well. For example, conservation of angular momentum
> dictates the structure of the lateral stress tensor calculations in
> MOM6. However, a quadratic or linear bottom drag term or flow around
> bathymetric features can be effective ways to extract angular
> momentum from the solid earth if there is any near-bottom flow (as
> is usually the case). However I do not think that we have carefully
> examined this in all possible cases, so if there is clear evidence
> that this is not the case, we would like to have that drawn to our
> intention.  (The "pretty well" has to do with the deliberate use of
> different definitions of the layer thickness at velocity points
> depending on the flow direction and speed and relative thicknesses
> of adjacent points, but that is a very long a detailed technical
> discussion, much of which will appear in the MOM6 documentation
> paper that we are writing.
>
>   2) The no-slip boundary conditions appear in the code in two
> places - in the estimate of relative vorticity at boundaries, and in
> the estimate of the shears at the boundaries (as determined by a 2-d
> land-mask). On a C-grid they do not dictate that the tangential
> velocity is actually 0 at any explicitly modeled location.
>
>   3) The ocean has no vertical sides. Density surfaces end where
> they intersect the (usually sloping) bottom or the free surface. To
> conserve angular momentum, we write the horizontal viscosity term on
> a C-grid as
>   du / dt = 1/h_u Div([h_q K_q, h_h K_h] Grad u)
> where u is the velocity, h_u is an estimate of the layer thickness
> at velocity points, h_q is an estimate of the thickness at vorticity
> points, h_h is the thickness at thickness points, and [K_h, K_q] are
> the Laplacian viscosities at the thickness and vorticity points.
> Everything except for h_q and h_u are well defined from 2nd order
> staggered discretizations or the C-grid variables themselves.
> Conservation of angular momentum requires that the same h_q appear
> in the u- and v- equations, and we have chosen to use simple
> arithmetic mean thicknesses for h_u in this term. Ensuring a finite
> acceleration when one or more of these thicknesses at velocity
> points go to 0 requires that the h_q also go to 0 in these
> circumstances. Therefore, we use the harmonic mean of the harmonic
> mean of the 2 values of h_u and harmonic mean of the 2 values of h_v
> (see line ~466 of MOM_hor_visc.F90, which starts hq = ...).  The
> harmonic mean of A and B is 2 A B / (A + B), and it has the nice
> property that it is a second order accurate average of A and B, but
> goes to 2 A when A << B.  This works well, but we do not
> currently apply land masks, and setting h over land to 0 has the
> effect of setting h_q at coastlines to 0, and disabling the fluxes
> with a no-slip boundary condition.
>
>  4) For the most part, in MOM6 we implement strong "lateral" drag
> via a vertical boundary condition with the CHANNEL_DRAG scheme,
> which calculates the bottom drag on a cell that partially intersects
> a sloping bottom.  This seems like the right approach for realistic
> simulations, but it obviously is not doing what we would like for
> idealized vertical-walled oceans.
>
>  5) Properly implementing a no-slip boundary condition will require
> changing the definition of h_q at coastal points using the (2-d)
> land-sea masks to determine when to replace the thicknesses of
> masked velocity points with values that are temporarily extrapolated
> from unmasked neighbors. This should work well enough for straight
> or convex coastlines, but will introduce some (probably acceptable)
> cross-contamination of u- and v- thicknesses at concave corners in
> coastlines.  Once we have written and tested this code modification,
> we will be closing out this issue.
>
>   Hopefully all this is helpful!
>
>   - Bob Hallberg
>
> p.s., The BT_STRONG_DRAG only pertains to bottom drag was a red
> herring in this case.
>
>
> On 10/07/2015 11:59 AM, Christopher L. Pitt Wolfe wrote:
>
> The problem is the jet. We only specify buoyancy
> forcing at the surface and southern sponge and forcing and
> sponges are zonally uniform, so there should be no source of
> zonal momentum. Therefore the jet is not there because of the
> forcing and there is no incompatibility between the forcing and
> boundary condition. Even if the jet were formed by some
> turbulent inverse cascade, the tangential flow should go to zero
> at the boundary due to no slip. What we see, however, is that
> the normal derivative of the tangential velocity goes to zero,
> suggesting that the model is giving us free-slip boundary
> conditions even though we asked for no-slip boundary conditions.
> —
> Reply to this email directly or view
> it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/230#issuecomment-146691422>.
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Comment by Hallberg-NOAA** [comment] 2015-10-09 12:30
There are no spurious momentum (or angular momentum) sources in
    MOM6.
    
      We routinely verify this with the "resting" test case.
    
      - Bob Hallberg
    
    On 10/08/2015 09:55 PM, Stephen Griffies wrote:
    Hi,
      
      I am only vaguely following the stencil details. But the
      discussion of
      spurious momentum sources makes me ask the following, perhaps
      off-the-mark
      questions, but wishing to be sure we are passing the "laugh test".
      
      With flat isopycnals and no momentum or buoyancy forcing at the
      ocean
      surface, does MOM6 keep the flow static if there is a vertical
      wall? What
      about sloping walls? Do answers to these questions depend on
      whether
      free-slip, no-slip, bottom drag, etc?
      
      Seems that the physically correct behaviour is static flow with
      horizontal
      isopycnals will stay static, regardless the frictional boundary
      conditions. Capisce?
      
      Steve
      
      
      
      On Thu, Oct 8, 2015 at 5:30 PM, Robert Hallberg
      <notifications@github.com>
      wrote:
      
      >
      >
      >
      >
      >
      > Hi Christopher and Suyash,
      >
      > Yes, you are absolutely right that the coastal lateral
      stresses
      > probably are being zeroed out in your idealized test case,
      depending
      > on how the layer thicknesses are being set in the halo points
      on
      > land.
      >
      > This has been a good discussion, that others might find
      helpful.
      > I originally encoded the no-slip boundary conditions, so
      perhaps I
      > can comment on a number of issues that have arisen in this
      > conversation thread.
      >
      > 1) MOM6 is written with the intention that it conserves
      angular
      > momentum pretty well. For example, conservation of angular
      momentum
      > dictates the structure of the lateral stress tensor
      calculations in
      > MOM6. However, a quadratic or linear bottom drag term or flow
      around
      > bathymetric features can be effective ways to extract angular
      > momentum from the solid earth if there is any near-bottom
      flow (as
      > is usually the case). However I do not think that we have
      carefully
      > examined this in all possible cases, so if there is clear
      evidence
      > that this is not the case, we would like to have that drawn
      to our
      > intention. (The "pretty well" has to do with the deliberate
      use of
      > different definitions of the layer thickness at velocity
      points
      > depending on the flow direction and speed and relative
      thicknesses
      > of adjacent points, but that is a very long a detailed
      technical
      > discussion, much of which will appear in the MOM6
      documentation
      > paper that we are writing.
      >
      > 2) The no-slip boundary conditions appear in the code in two
      > places - in the estimate of relative vorticity at boundaries,
      and in
      > the estimate of the shears at the boundaries (as determined
      by a 2-d
      > land-mask). On a C-grid they do not dictate that the
      tangential
      > velocity is actually 0 at any explicitly modeled location.
      >
      > 3) The ocean has no vertical sides. Density surfaces end
      where
      > they intersect the (usually sloping) bottom or the free
      surface. To
      > conserve angular momentum, we write the horizontal viscosity
      term on
      > a C-grid as
      > du / dt = 1/h_u Div([h_q K_q, h_h K_h] Grad u)
      > where u is the velocity, h_u is an estimate of the layer
      thickness
      > at velocity points, h_q is an estimate of the thickness at
      vorticity
      > points, h_h is the thickness at thickness points, and [K_h,
      K_q] are
      > the Laplacian viscosities at the thickness and vorticity
      points.
      > Everything except for h_q and h_u are well defined from 2nd
      order
      > staggered discretizations or the C-grid variables themselves.
      > Conservation of angular momentum requires that the same h_q
      appear
      > in the u- and v- equations, and we have chosen to use simple
      > arithmetic mean thicknesses for h_u in this term. Ensuring a
      finite
      > acceleration when one or more of these thicknesses at
      velocity
      > points go to 0 requires that the h_q also go to 0 in these
      > circumstances. Therefore, we use the harmonic mean of the
      harmonic
      > mean of the 2 values of h_u and harmonic mean of the 2 values
      of h_v
      > (see line ~466 of MOM_hor_visc.F90, which starts hq = ...).
      The
      > harmonic mean of A and B is 2 A B / (A + B), and it has the
      nice
      > property that it is a second order accurate average of A and
      B, but
      > goes to 2 A when A << B. This works well, but we do not
      > currently apply land masks, and setting h over land to 0 has
      the
      > effect of setting h_q at coastlines to 0, and disabling the
      fluxes
      > with a no-slip boundary condition.
      >
      > 4) For the most part, in MOM6 we implement strong "lateral"
      drag
      > via a vertical boundary condition with the CHANNEL_DRAG
      scheme,
      > which calculates the bottom drag on a cell that partially
      intersects
      > a sloping bottom. This seems like the right approach for
      realistic
      > simulations, but it obviously is not doing what we would like
      for
      > idealized vertical-walled oceans.
      >
      > 5) Properly implementing a no-slip boundary condition will
      require
      > changing the definition of h_q at coastal points using the
      (2-d)
      > land-sea masks to determine when to replace the thicknesses
      of
      > masked velocity points with values that are temporarily
      extrapolated
      > from unmasked neighbors. This should work well enough for
      straight
      > or convex coastlines, but will introduce some (probably
      acceptable)
      > cross-contamination of u- and v- thicknesses at concave
      corners in
      > coastlines. Once we have written and tested this code
      modification,
      > we will be closing out this issue.
      >
      > Hopefully all this is helpful!
      >
      > - Bob Hallberg
      >
      > p.s., The BT_STRONG_DRAG only pertains to bottom drag was a
      red
      > herring in this case.
      >
      >
      > On 10/07/2015 11:59 AM, Christopher L. Pitt Wolfe wrote:
      >
      > The problem is the jet. We only specify buoyancy
      > forcing at the surface and southern sponge and forcing and
      > sponges are zonally uniform, so there should be no source of
      > zonal momentum. Therefore the jet is not there because of the
      > forcing and there is no incompatibility between the forcing
      and
      > boundary condition. Even if the jet were formed by some
      > turbulent inverse cascade, the tangential flow should go to
      zero
      > at the boundary due to no slip. What we see, however, is that
      > the normal derivative of the tangential velocity goes to
      zero,
      > suggesting that the model is giving us free-slip boundary
      > conditions even though we asked for no-slip boundary
      conditions.
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/NOAA-GFDL/MOM6/issues/230#issuecomment-146691422>.
      >
      
      
      
      -- 
      Dr. Stephen M. Griffies
      NOAA Geophysical Fluid Dynamics Lab
      201 Forrestal Road
      Princeton, NJ 08542
      USA
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by adcroft** [comment] 2015-10-09 12:51
Good point - I forget about these small tests too often. The 'seamount' example also tests this as well as demonstrates the absence of spontaneous motion in several coordinate systems over topography.

A forced Taylor cap over a seamount might be a good candidate for exercising sponges? I vaguely recall someone using that test in their thesis...

**Closed** 2015-10-13 19:22 UTC
