### ISSUE TITLE
Off-by-one error in mercator grid initialization using symmetric grid

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#273] opened 2016-04-29 04:48 UTC
The local variables yq, yv (xq, xu) are not initialized at j=0 (i=0). This error propagates into grid variables geoLon/Lat*, dx*, dy* etc.

For example the loop at src/initialization/MOM_grid_initialize.F90:1002 ranges from jsg-njhalo, jeg+njhalo but the yq, yz j index at lines 1017 and 1018 offset this by 4 giving a range from 1-188, not the 0-188 expected on symmetric.

I'll send a fix presently.

**Comment by Hallberg-NOAA** [comment] 2016-04-29 13:31
Well spotted. To fix this, we would need to add the equivalent of lines 1006, 1007, 1009 and 1016-1019 for j= G%jsg-G%Domain%njhalo-1.  Unfortunately, this needs to be done carefully because the starting for iterating to find y_h in find_root is y_q and for y_h the starting point is y_q. find_root may be polishing the root well enough the starting value of the iteration doesn't matter, but then again the order of these calculations might matter. Probably the better approach would be to do the calculation for all points in the global halo starting from y_q for south_lat, and then restart the iteration moving into the global computational domain. Not doing this would make it challenging to get results that reproduce for symmetric and non-symmetric cases, and might cause answers to change when the halo size is changed (this might already be an issue).

Do you want to offer a fix, Nick, or would you like me to field this one?

**Comment by nicjhan** [comment] 2016-04-30 00:20
@Hallberg-NOAA OK this is more detailed than than my fix! Yes, could you please look after it.

**Comment by Hallberg-NOAA** [comment] 2016-05-03 22:31
Thanks for finding this, @nicjhan!  This issue is addressed by commit
https://github.com/NOAA-GFDL/MOM6/commit/eb681a24286993df8ad1c1bb7d9b890c9423a2cd

**Closed by Hallberg-NOAA** 2016-05-03 22:31 UTC
