### ISSUE TITLE
Dynamic + symmetric memory fails for ocean_only/global_ALE/ experiments (z and layer)

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#271] opened 2016-04-26 21:06 UTC
Compiling with `config_src/dynamic_symmetric/MOM_memory.h` for intel and gnu compilers yields a segmentation violation at runtime:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
MOM6               00000000008D74BA  mom_vert_friction         782  MOM_vert_friction.F90
MOM6               0000000000A74CD2  mom_dynamics_spli         799  MOM_dynamics_split_RK2.F90
MOM6               000000000097A4E2  mom_mp_step_mom_          860  MOM.F90
MOM6               00000000007121DD  MAIN__                    426  MOM_driver.F90
MOM6               00000000004006AC  Unknown               Unknown  Unknown
MOM6               00000000013D9834  Unknown               Unknown  Unknown
MOM6               000000000040057D  Unknown               Unknown  Unknown
```

We suspect a memory issue (writing out-of-bounds) because in a debugger an associated array becomes unassociated for no obvious reason.

PGI comes down with a different problem that we assume is related:
```
FATAL from PE     3: MPP_DO_GROUP_UPDATE: this interface does not support folded_south, folded_west of folded_east, contact developer
```

**Comment by Hallberg-NOAA** [comment] 2016-04-26 22:36
This problem is almost certainly a segmentation violation that occurs earlier in the code (probably in one of the non-blocking group halo updates), that causes a corruption of some of the allocatable arrays in the vertvisc_type. As further evidence of this, swapping the order in which two allocatable arrays are listed in the vertvisc_CS type changes the line numbers in which the model fails. In both cases the model fails when the first arrays listed in the vertvisc_CS type are accessed.

The changes in the order of arrays in the type indicated by:
> diff --git a/src/parameterizations/vertical/MOM_vert_friction.F90 b/src/parameterizations/vertical/MOM_vert_friction.F90
index 3be335c..4113fc2 100644
--- a/src/parameterizations/vertical/MOM_vert_friction.F90
+++ b/src/parameterizations/vertical/MOM_vert_friction.F90
@@ -126,12 +126,12 @@ type, public :: vertvisc_CS ; private
   type(time_type) :: rampStartTime ! The time that the ramping of CFL_trunc starts
 
-  real ALLOCABLE_, dimension(NIMEMB_PTR_,NJMEM_,NK_INTERFACE_) :: &
-    a_u                ! The u-drag coefficient across an interface, in m s-1.
-  real ALLOCABLE_, dimension(NIMEMB_PTR_,NJMEM_,NKMEM_) :: &
-    h_u                ! The effective layer thickness at u-points, m or kg m-2.
   real ALLOCABLE_, dimension(NIMEM_,NJMEMB_PTR_,NK_INTERFACE_) :: &
     a_v                ! The v-drag coefficient across an interface, in m s-1.
   real ALLOCABLE_, dimension(NIMEM_,NJMEMB_PTR_,NKMEM_) :: &
     h_v                ! The effective layer thickness at v-points, m or kg m-2.
+  real ALLOCABLE_, dimension(NIMEMB_PTR_,NJMEM_,NK_INTERFACE_) :: &
+    a_u                ! The u-drag coefficient across an interface, in m s-1.
+  real ALLOCABLE_, dimension(NIMEMB_PTR_,NJMEM_,NKMEM_) :: &
+    h_u                ! The effective layer thickness at u-points, m or kg m-2.
   real, pointer, dimension(:,:) :: &
     a1_shelf_u => NULL(), & ! The surface coupling coefficients under ice

lead to the error messages:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
MOM6.exec_sym      0000000000CDCB20  mom_vert_friction         909  MOM_vert_friction.F90
MOM6.exec_sym      0000000000F22FBE  mom_dynamics_spli         799  MOM_dynamics_split_RK2.F90
MOM6.exec_sym      0000000000DD6C84  mom_mp_step_mom_          860  MOM.F90
MOM6.exec_sym      0000000000AD064D  MAIN__                    426  MOM_driver.F90
MOM6.exec_sym      000000000040070C  Unknown               Unknown  Unknown

As further evidence that this may be due to a non-blocking halo update, when running in a debugger there are times when the allocatable arrays are corrupted as early as line 724 (and perhaps earlier) of MOM_dynamics_split_RK2.F90 and other runs when the arrays can seem fine as late as line 798 of MOM_dynamics_split_RK2.F90.

**Comment by nicjhan** [comment] 2016-05-04 07:31
I've been running global_ALE/z(layer) with and without Valgrind using a intel+gnu debug builds and -fpe0 (full FP exceptions) turned on.  The problems I've run into are #273 (?), #274, #278, #264/#277, and #280. These were array bounds mismatches or floating invalid exceptions caused by reading uninitalized memory.  #278, #280 are innocuous but the others may have a larger impact. 

After fixing/avoiding these issues my 10 day run finishes. Valgrind now only reports a single use of bad memory, however this is not within MOM (I think it's in the valgrind MPI wrappers, which is not unprecedented. I still want to fix this one though). I think Valgrind not reporting any errors on code of this size is unusual, and very reassuring.

@adcroft if you get time can you please try a run with these fixes? (It will take another few days for me to try this on your machine). In the meantime I'll look further into the remaining error.

P.S. In terms of seg faults I was getting something like this:

`FATAL from PE   376: MPP_DO_GROUP_UPDATE: this interface does not support folded_south, folded_west of folded_east, contact developer`

Followed by

`forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
MOM6               0000000001513EB1  Unknown               Unknown  Unknown
MOM6               0000000001512607  Unknown               Unknown  Unknown
MOM6               00000000014C2DB4  Unknown               Unknown  Unknown
MOM6               00000000014C2BC6  Unknown               Unknown  Unknown
MOM6               000000000145AE2F  Unknown               Unknown  Unknown
MOM6               000000000145EA8D  Unknown               Unknown  Unknown
libpthread.so.0    00002B26E73237E0  Unknown               Unknown  Unknown
MOM6               00000000011DB122  mpp_domains_mod_m         398  mpp_group_update.h
MOM6               0000000000BE3693  mom_domains_mp_do         821  MOM_domains.F90
MOM6               0000000000A4C5FA  mom_barotropic_mp        3258  MOM_barotropic.F90
MOM6               0000000000A03819  mom_barotropic_mp         986  MOM_barotropic.F90
MOM6               0000000000D75967  mom_dynamics_spli         753  MOM_dynamics_split_RK2.F90
MOM6               0000000000C4E56A  mom_mp_step_mom_          860  MOM.F90
MOM6               00000000008DA6BC  MAIN__                    426  MOM_driver.F90
MOM6               000000000040BE4E  Unknown               Unknown  Unknown
libc.so.6          00002B26E754FD5D  Unknown               Unknown  Unknown
MOM6               000000000040BD59  Unknown               Unknown  Unknown`

Surprisingly this went away after #274. I can only guess that #274 which happens around line 709 of step_MOM_dyn_split_RK2() overran/corrupted size information of stack variables ... this stack corruption then lead to things going haywire on the return to step_MOM_dyn_split_RK2() eventually leading to the segfault we see.

**Comment by Hallberg-NOAA** [comment] 2016-05-04 14:56
After testing here at GFDL, I concur with @nicjhan  that this issue has been resolved, and I am closing this issue.  Well done  @nicjhan!

**Closed by Hallberg-NOAA** 2016-05-04 14:56 UTC
Labels: bug
