### ISSUE TITLE
Floating divide by zero in mixed_layer_restrat_2d

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#299] opened 2016-05-23 05:03 UTC
This happens with symmetric memory only. 

The error output is:

MOM6               0000000002C55210  mom_continuity_pp        1021  MOM_continuity_PPM.F90
MOM6               0000000002C0D8D1  mom_continuity_pp         571  MOM_continuity_PPM.F90
MOM6               0000000002BBDC0A  mom_continuity_pp         216  MOM_continuity_PPM.F90
MOM6               0000000001291249  mom_continuity_mp         156  MOM_continuity.F90
MOM6               000000000323F36B  mom_dynamics_spli         531  MOM_dynamics_split_RK2.F90
MOM6               0000000002D81295  mom_mp_step_mom_          861  MOM.F90
MOM6               0000000001BA84F9  MAIN__                    426  MOM_driver.F90

Full run output can be found here:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-mixed_layer_restrat_2d,memory_type=dynamic_symmetric/15/console

**Comment by Hallberg-NOAA** [comment] 2016-05-24 22:57
This was caused by an improper declaration of array sizes in two initialization subroutine arguments. This issue is addressed and closed by MOM6 commit NOAA-GFDL/MOM6@27ec124bdd18d79b91519eaf76af823f55c54660

**Closed by Hallberg-NOAA** 2016-05-24 22:57 UTC
