### ISSUE TITLE
Need to test for presence, appropriate version of FMS library

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/MOM6#1394] opened 2021-05-06 15:07 UTC
The MOM6 build system needs to check for the presence and version of the FMS library, to make sure a sufficient version is ready.

This is part of a larger effort to have all components in the UFS check for their required dependent libraries.

**Comment by marshallward** [comment] 2021-05-06 15:26
Could you clarify what you mean by version checking, and how this would work?  Currently MOM6 supports multiple versions of FMS, and is generally left to the user to select the target FMS library.

Currently we do not attempt to detect compatibility, which we would like to do once our support for FMS2 I/O has stabilized.

If you have an example where this has been implemented that would help out here.

**Comment by edwardhartnett** [comment] 2021-05-06 15:36
What I mean is that MOM6 should look for the FMS library, and ensure that it's version is supported.

For example, here's some checking from the UFS_UTILS project (https://github.com/NOAA-EMC/UFS_UTILS):

```
# Find packages.
find_package(NetCDF 4.3.3 REQUIRED C Fortran)
find_package(MPI REQUIRED C Fortran)
find_package(ESMF 8.0.0 REQUIRED)

if(OPENMP)
  find_package(OpenMP REQUIRED COMPONENTS Fortran)
endif()

find_package(sfcio 1.4.0 REQUIRED)
find_package(w3nco 2.4.0 REQUIRED)
find_package(bacio 2.4.0 REQUIRED)
find_package(nemsio 2.5.0 REQUIRED)
find_package(sigio 2.3.0 REQUIRED)
find_package(sp 2.3.3 REQUIRED)
find_package(ip 3.3.3 REQUIRED)
find_package(g2 3.4.0 REQUIRED)
find_package(wgrib2 2.0.8 REQUIRED)
```

We need every package in the UFS stack to check for everything it needs, including versions and whatever features are depended upon (for example, if you require netCDF with parallel I/O, we can check for that).

**Comment by edwardhartnett** [comment] 2021-05-06 16:18
OK so it seems you need to do this in autoconf. Here's a sample from netcdf-fortran. This code checks netcdf-c for everything it needs to know (and it needs to know everything). Then it sets some Automake conditionals and takes whatever other actions are indicated, adjusting the build of netcdf-fortran to the way that netcdf-c was built.

For example, if netcdf-c was build without netcdf-4, then netcdf-fortran will also build without netcdf-4.

In the case of MOM6 and the FMS, you would check for the version(s) you need, and error out if not found. Usually you do this by looking for a function that was introduced in this version. This is a bit clunky, so what a lot of packages (like netcdf-c) do is also install a .h file with a bunch of pre-processor defines set to the correct values.

(In fact, I intend to add such a header file for FMS as well, but have not yet had time...)

```
# Find the netCDF header and library.
AC_CHECK_HEADERS([netcdf.h], [], [AC_MSG_ERROR([netcdf.h could not be found. Please set CPPFLAGS.])])
AC_SEARCH_LIBS([nc_open], [netcdf], [],
			  [AC_MSG_ERROR([Could not link to netcdf C library. Please set LDFLAGS; for static builds set LIBS to the results of nc-config --libs.])])

# See if various functions are available
AC_CHECK_FUNCS([nc_def_opaque nccreate nc_set_log_level oc_open nc_def_var_szip])

# Starting with version 4.7.4, netcdf-c has function nc_def_var_szip().
if test "x$ac_cv_func_nc_def_var_szip" != xyes; then
   AC_MSG_ERROR([netcdf-c version 4.7.4 or greater is required])
fi

nc_build_v2=no
nc_build_v4=no
nc_has_logging=no
nc_has_dap=no

AC_CHECK_FUNCS([nc_get_chunk_cache_ints],[nc_build_v4=yes],[nc_build_v4=no])
test "x$ac_cv_func_nccreate" = xyes && nc_build_v2=yes
test "x$ac_cv_func_nc_set_log_level" = xyes && nc_has_logging=yes
test "x$ac_cv_func_oc_open" = xyes && nc_has_dap=yes

if test "x$nc_build_v4" = xyes; then
   AC_DEFINE([USE_NETCDF4], [1], [if true, build netCDF-4])
fi

if test "x$nc_has_logging" = xyes; then
   AC_DEFINE([LOGGING], [1], [if true, C library contains logging])
fi
AC_MSG_CHECKING([netCDF logging present])
AC_MSG_RESULT([$nc_has_logging])

AC_MSG_CHECKING([netCDF v2 API present])
AC_MSG_RESULT([$nc_build_v2])
AC_MSG_CHECKING([netCDF-4 present])
AC_MSG_RESULT([$nc_build_v4])

AC_MSG_CHECKING([whether to test the filter API])
AC_ARG_ENABLE([filter-test],
              [AS_HELP_STRING([--enable-filter-test],
                              [Run filter tests: requires access to the plugins directory in a netcdf-c build.])])
test "x$enable_filter_test" = xyes || enable_filter_test=no
AC_MSG_RESULT($enable_filter_test)

AM_CONDITIONAL([USE_NETCDF4], [test "x$nc_build_v4" = xyes])
AM_CONDITIONAL([BUILD_V2], [test "x$nc_build_v2" = xyes])
AM_CONDITIONAL([HAS_LOGGING], [test "x$nc_has_logging" = xyes])
AM_CONDITIONAL([USE_LOGGING], [test "x$nc_has_logging" = xyes])
AM_CONDITIONAL([BUILD_DAP], [test "x$nc_has_dap" = xyes])
AM_CONDITIONAL([BUILD_PNETCDF], [test "x$nc_has_pnetcdf" = xyes])
AM_CONDITIONAL([BUILD_PARALLEL4], [test "x$nc_has_parallel4" = xyes])
AM_CONDITIONAL([BUILD_PARALLEL], [test "x$nc_has_pnetcdf" = xyes -o "x$nc_has_parallel4" = xyes])
AM_CONDITIONAL([TEST_FILTERS], [test "x$enable_filter_test" = xyes])

```

**Comment by marshallward** [comment] 2021-05-06 16:55
I believe that we can implement something like you have outlined in our autoconf build.

I am not sure one can easily encapsulate the history of the FMS API into a few simple tests, so I would suggest we proceed iteratively.

Are the FMS requirements for UFS well-defined right now?  If it is simply a matter of detecting FMS2 I/O, for example, then that is a good place to start.

**Comment by edwardhartnett** [comment] 2021-05-06 18:19
You are one of the two packages in the UFS that uses FMS, so I will turn around and ask you to define what MOM6 needs from FMS. ;-)

One can and must encapsulate the history of FMS into a few simple tests. ;-). As I mentioned, if that's not sufficient, I can add a summary header file to the FMS build which will contain the info we need.

MOM6 must not attempt to build with a missing or out of date FMS library.

**Comment by marshallward** [comment] 2021-05-06 18:51
The autoconf build checks if FMS is available before attempting to build.  So that part of your criteria is met.  If that is all that is required, then we can close this issue.

There is opportunity to refine the build system if, for example, the other component (FV3, I'm guessing) requires the FMS2 I/O API.  We plan to implement this once we are satisfied that MOM6 and SIS2 run under FMS2 I/O.

But as things stand, I do not know what the the problem is and what needs to be solved.

I am concerned that these issues are getting populated with generalities and dispensation of unsolicited advice wrapped up as operational issues.  I'm happy to discuss and debate our design decisions, but those belong in the Discussions tab.

**Comment by edwardhartnett** [comment] 2021-05-06 19:01
Good that it checks for FMS.

Does it check for appropriate version?

That is, if there is a version of FMS that is older than what you need, will configure fail?

**Comment by marshallward** [comment] 2021-05-06 19:26
No, not at this time.  The current test is very minimal; we only test for `fms_init` and do not explicitly check for anything like a version string (if such a thing even exists).

This is a good suggestion, though it will take a bit of FMS archaeology to identify the latest build which can be used.  But I'll look into this.

The issue is slightly complicated by the fact that we support two FMS interfaces, one with and the other without FMS2 I/O.   It is also possible to introduce additional interfaces if needed.  Do you know which one UFS intends to use?

**Comment by edwardhartnett** [comment] 2021-05-06 20:37
OK, this is how the conversation started. ;-)

You need to check the versions of packages, as well as their presence. 

You should also be doing this for netcdf and other third party libraries you use.

I do not think that UFS uses FMS I/O at all. But if it does, it's not FMS2 I/O.

**Closed** 2021-05-26 13:27 UTC
